# Generated by Django 5.2.7 on 2025-10-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.TextField(blank=True, help_text='Comma-separated list of actors', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='aka',
            field=models.CharField(blank=True, help_text='Also Known As (alternative titles)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, help_text='IMDB ID (e.g., tt1234567)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_iv',
            field=models.CharField(blank=True, help_text='IMDB IV identifier', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rank',
            field=models.FloatField(blank=True, help_text='IMDB ranking', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_url',
            field=models.URLField(blank=True, help_text='IMDB URL', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='photo_height',
            field=models.IntegerField(blank=True, help_text='Poster image height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='photo_width',
            field=models.IntegerField(blank=True, help_text='Poster image width in pixels', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Uploaded poster image', null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, help_text='External poster image URL', null=True),
        ),
    ]
